# Site settings
title: Mārtiņš Mihailovs
tagline: Vēstules
description: "Describe your website."
#Comment out url when working locally to resolve base urls correctly
url: http://martinsmihailovs.com
baseurl: ""

include:  ['_pages']

exclude: [
  'node_modules',
  'Gruntfile.js',
  'package.json',
  'README.md'
]

# Owner/author information
owner:
  name: Mārtiņš Mihailovs
  occupation: UX/UI dizainers / web izstrādātājs
  age: 29
  email: m.mihailovs@gmail.com
  twitter: Mar7ins
  github: MartinsMihailovs
  location: "Rīga, Latvija"

tools:
  standards: "HTML, CSS, JavaScript, Jekyll"
  software: "git"

markdown: kramdown
permalink: /:categories/:title

production: false
